---
title: "simple_bayes"
output: html_document
---

```{r include=F}
library(extraDistr)
library(distr)
library(ggplot2)
library(rstan)
suppressPackageStartupMessages(require(ggplot2))
suppressPackageStartupMessages(require(dplyr))
suppressPackageStartupMessages(require(bayesplot))

library(AmesHousing)

```


# Simple linear regression
```{r}
ames_df2 = make_ordinal_ames()

y = ames_df2$Sale_Price
x = ames_df2$Lot_Area

data_list <- list(
  N = length(x),
  xs = x,
  ys = y,
  x_pred = 5000
)

```

```{r}



fit <- stan(
  file = "simple_bayes.stan", 
  data = data_list, 
  iter = 2000, 
  chains = 4,
  seed = 447
)



```



```{r}
traceplot(fit, pars = c("slope", "sigma"))
summary(fit)$summary

```

```{r}
posterior_y <- extract(fit)$y_pred
hist(posterior_y, main = "Posterior Predictive Distribution", xlab = "Predicted y")
abline(v = mean(posterior_y), col = "red")

```

```{r}
posterior <- extract(fit)
slope_post_mean <- mean(posterior$slope)
fitted_vals <- slope_post_mean * x
residuals <- y - fitted_vals


plot(fitted_vals, residuals, main = "Residuals vs Fitted", xlab = "Fitted", ylab = "Residuals")
abline(h = 0, col = "red")

```

# Multiple regression
```{r}
vars <- c("Sale_Price", "Lot_Area", "Overall_Qual", "Year_Built", "Neighborhood", "Bldg_Type")
ames_small <- ames_df2[, vars]
ames_small <- na.omit(ames_small)


X <- model.matrix(Sale_Price ~ . - 1, data = ames_small)
# colnames(X)

# X <- scale(X)

y <- ames_small$Sale_Price
x_pred <- X[1, ]

data_list <- list(
  N = nrow(X),
  K = ncol(X),
  X = X,
  y = y,
  x_pred = x_pred
)

```

```{r}
fit <- stan(
  file = "multivar_bayes.stan",
  data = data_list,
  iter = 2000,
  chains = 4,
  seed = 447
)
```

```{r}
traceplot(fit)

```

```{r}
summary(fit)$summary

```

```{r}
posterior_y <- extract(fit)$y_pred
hist(posterior_y, main = "Posterior Predictive Distribution", xlab = "Predicted y")
abline(v = mean(posterior_y), col = "red")

```


# Hiearchical model
```{r}

ames_small$neigh_id <- as.integer(factor(ames_small$Neighborhood))
G <- length(unique(ames_small$neigh_id))

X <- model.matrix(Sale_Price ~ . - Neighborhood - 1, data = ames_small)
X <- scale(X)

y <- ames_small$Sale_Price
x_pred <- X[1, ]

data_list <- list(
  N = nrow(X),
  K = ncol(X),
  X = X,
  y = y,
  G = G,
  gid = ames_small$neigh_id,
  x_pred = x_pred
)


fit <- stan(
  file = "hier_neigh_model.stan",
  data = data_list,
  iter = 1000,
  chains = 4,
  seed = 447
)

```

With all features
```{r}

ames_df2_na = na.omit(ames_df2)
ames_df2_na$neigh_id <- as.integer(factor(ames_df2_na$Neighborhood))
G <- length(unique(ames_df2_na$neigh_id))

X <- model.matrix(Sale_Price ~ . - Neighborhood - 1, data = ames_df2_na)
X <- scale(X)

y <- ames_df2_na$Sale_Price
x_pred <- X[1, ]

data_list2 <- list(
  N = nrow(X),
  K = ncol(X),
  X = X,
  y = y,
  G = G,
  gid = ames_df2_na$neigh_id,
  x_pred = x_pred
)


fit <- stan(
  file = "hier_neigh_model.stan",
  data = data_list2,
  iter = 1000,
  chains = 4,
  seed = 447
)
```


```{r}
traceplot(fit)
```

```{r}
summary(fit)$summary
```

## Justification for hiearchical model
Sale price is different based on neighborhood
```{r}
ggplot(ames_df2, aes(x = Neighborhood, y = Sale_Price)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Sale Price by Neighborhood")
```

```{}
library(leaps)
regfit_full <- regsubsets(Sale_Price ~ ., data = ames_df2_na, nvmax = 10, method = "exhaustive", really.big = T)

```